In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]

In [3]:
type(l)

list

In [4]:
# Converting python list to numpy array.
np.array(l)

array([1, 2, 3, 4, 4])

In [5]:
# Creating a numpy array.
# Arrays must have symmetric dimensions.
a1 = np.array([[1,2,3],[3,4,5]])

In [6]:
a1


array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [8]:
a2


array([[[1, 2, 3],
        [4, 5, 6]]])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
# Checking the dimension of the array.
a.ndim

1

In [12]:
a1.ndim

2

In [13]:
a2.ndim

3

In [14]:
a3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [15]:
a3.ndim

3

In [16]:
l = [1,2,3,4]

In [17]:
a = np.asarray(l)

In [18]:
m = np.matrix(l)

In [19]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [20]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [21]:
# Shallow Copy
# changes in a1 will be reflected in a and vice versa
a1 = a

In [22]:
a

array([1, 2, 3, 4])

In [23]:
a[0]

1

In [24]:
a[0] = 10

In [25]:
a

array([10,  2,  3,  4])

In [26]:
a1

array([10,  2,  3,  4])

In [27]:
# Deep copy -> np.copy() 
# changes in a2 will not reflect in a
a2 = np.copy(a)

In [28]:
a2

array([10,  2,  3,  4])

In [29]:
a2[2] = 30

In [30]:
a2

array([10,  2, 30,  4])

In [31]:
a

array([10,  2,  3,  4])

In [32]:
np.fromfunction(lambda i,j : i==j, (3,4))
# 3 - rows
# 4 - columns
# i = x axis
# j = y axis
# if i==j -> True
# if i!-j -> False
# Creates only 2D array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [33]:
np.random.rand(2,3)
# creates a array with 2 rows , 3 columns with random data.

array([[0.46614685, 0.29234734, 0.25176093],
       [0.2873817 , 0.45274794, 0.54170312]])

In [34]:
np.random.rand(2,3,3)
# creates a matrix of 3 rows and 3 columns with 2 layers
# i.e it created 3D array.

array([[[0.57418663, 0.01779242, 0.14339533],
        [0.91794448, 0.23391151, 0.92571385],
        [0.38340012, 0.12899139, 0.32107563]],

       [[0.43078687, 0.93426998, 0.16857991],
        [0.11589216, 0.48151156, 0.3375222 ],
        [0.37245852, 0.45723934, 0.53752914]]])

In [35]:
np.random.randn(2,3,3)
# random.randn creates a array with the standard normal distribution where mean = 0 & std deviation = 1

array([[[ 0.10801474, -1.67918134,  0.73985803],
        [ 1.85841842,  0.84846653, -0.3158177 ],
        [-0.84126105,  0.66375024,  0.24300999]],

       [[ 0.5736194 , -1.72058051,  1.16480065],
        [ 0.06171373, -0.58609212,  0.72174674],
        [-0.68317397,  1.48042342,  0.29391625]]])

In [36]:
np.random.randint(0,10)
# gives random int between 0 and 10.

7

In [37]:
np.random.randint(0,10,(4,4,4))
# it gives matrix of 4 X 2 which have values between 0 and 10.

array([[[4, 3, 6, 3],
        [7, 4, 8, 6],
        [7, 1, 3, 2],
        [9, 8, 1, 6]],

       [[1, 5, 9, 1],
        [8, 9, 0, 6],
        [5, 7, 8, 8],
        [5, 3, 7, 4]],

       [[8, 8, 3, 9],
        [4, 1, 2, 3],
        [7, 0, 4, 9],
        [9, 0, 5, 0]],

       [[1, 6, 2, 6],
        [2, 6, 2, 5],
        [9, 9, 2, 6],
        [8, 6, 9, 8]]])

In [38]:
d = np.random.randn(3,4)

In [39]:
d

array([[-1.73315072, -1.11593848, -0.07666961,  1.93100562],
       [-0.52942434,  1.19341496, -0.99689225, -1.22448361],
       [ 0.14703976,  0.64029353,  0.69655343, -1.13016878]])

In [40]:
# lets convert np array into pandas dataframe

import pandas as pd

In [41]:
pd.DataFrame(d)

0         1         2         3
0 -1.733151 -1.115938 -0.076670  1.931006
1 -0.529424  1.193415 -0.996892 -1.224484
2  0.147040  0.640294  0.696553 -1.130169

In [42]:
d1 = np.random.randint(0,10,(4,4,4))


In [44]:
pd.DataFrame(d1)
# So it cannot convert 3d data into Data Frame

ValueError: Must pass 2-d input. shape=(4, 4, 4)

In [53]:
# Using reshape function we can do it.
# d1 has total 64 elements, which we need to reshape into 2d array
# so we can do it 16*4, 32*2 ,etc.
# then we can use pandas DataFrame function to convert into Data Frame.
# 1st arrgument = rows & 2md argument = columns
d1.reshape(16,4)

array([[4, 4, 3, 8],
       [3, 1, 7, 3],
       [6, 6, 1, 9],
       [0, 8, 6, 4],
       [7, 4, 5, 9],
       [3, 9, 5, 0],
       [8, 7, 6, 8],
       [1, 9, 6, 0],
       [7, 3, 1, 8],
       [8, 4, 2, 7],
       [8, 5, 8, 8],
       [0, 7, 0, 0],
       [2, 5, 5, 9],
       [9, 2, 4, 0],
       [8, 6, 9, 6],
       [4, 5, 2, 8]])

In [54]:
pd.DataFrame(d1.reshape(16,4))

0  1  2  3
0   4  4  3  8
1   3  1  7  3
2   6  6  1  9
3   0  8  6  4
4   7  4  5  9
5   3  9  5  0
6   8  7  6  8
7   1  9  6  0
8   7  3  1  8
9   8  4  2  7
10  8  5  8  8
11  0  7  0  0
12  2  5  5  9
13  9  2  4  0
14  8  6  9  6
15  4  5  2  8

In [55]:
# we can also reshape any array by passing a second argument of reshape as -ve number.
# Basically, -ve will identyfy the missing value and fill it automatically to convert the array into 2d array.

d1.reshape(8,-1)

array([[4, 4, 3, 8, 3, 1, 7, 3],
       [6, 6, 1, 9, 0, 8, 6, 4],
       [7, 4, 5, 9, 3, 9, 5, 0],
       [8, 7, 6, 8, 1, 9, 6, 0],
       [7, 3, 1, 8, 8, 4, 2, 7],
       [8, 5, 8, 8, 0, 7, 0, 0],
       [2, 5, 5, 9, 9, 2, 4, 0],
       [8, 6, 9, 6, 4, 5, 2, 8]])

In [52]:
d1.reshape(4,-100)

array([[4, 4, 3, 8, 3, 1, 7, 3, 6, 6, 1, 9, 0, 8, 6, 4],
       [7, 4, 5, 9, 3, 9, 5, 0, 8, 7, 6, 8, 1, 9, 6, 0],
       [7, 3, 1, 8, 8, 4, 2, 7, 8, 5, 8, 8, 0, 7, 0, 0],
       [2, 5, 5, 9, 9, 2, 4, 0, 8, 6, 9, 6, 4, 5, 2, 8]])

In [58]:
d1 # the reshape is temparary, we need to store it in any variable.

array([[[4, 4, 3, 8],
        [3, 1, 7, 3],
        [6, 6, 1, 9],
        [0, 8, 6, 4]],

       [[7, 4, 5, 9],
        [3, 9, 5, 0],
        [8, 7, 6, 8],
        [1, 9, 6, 0]],

       [[7, 3, 1, 8],
        [8, 4, 2, 7],
        [8, 5, 8, 8],
        [0, 7, 0, 0]],

       [[2, 5, 5, 9],
        [9, 2, 4, 0],
        [8, 6, 9, 6],
        [4, 5, 2, 8]]])

In [59]:
d2 = d1.reshape(4,-100)

In [60]:
d2

array([[4, 4, 3, 8, 3, 1, 7, 3, 6, 6, 1, 9, 0, 8, 6, 4],
       [7, 4, 5, 9, 3, 9, 5, 0, 8, 7, 6, 8, 1, 9, 6, 0],
       [7, 3, 1, 8, 8, 4, 2, 7, 8, 5, 8, 8, 0, 7, 0, 0],
       [2, 5, 5, 9, 9, 2, 4, 0, 8, 6, 9, 6, 4, 5, 2, 8]])

In [61]:
pd.DataFrame(d2)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0   4   4   3   8   3   1   7   3   6   6   1   9   0   8   6   4
1   7   4   5   9   3   9   5   0   8   7   6   8   1   9   6   0
2   7   3   1   8   8   4   2   7   8   5   8   8   0   7   0   0
3   2   5   5   9   9   2   4   0   8   6   9   6   4   5   2   8