In [1]:
import numpy as np

In [6]:
# Range Generate data based on upper and lower bound range.
range(10)

range(0, 10)

In [7]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [10]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [12]:
list(range(1,10.5))
# it does not work for floating point number

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
# But we can generate floating point data using numpy

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(.5,10.5)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [20]:
np.arange(4,-5,-1)

array([ 4,  3,  2,  1,  0, -1, -2, -3, -4])

In [21]:
np.arange(4,-5,-0.5)

array([ 4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. , -0.5, -1. ,
       -1.5, -2. , -2.5, -3. , -3.5, -4. , -4.5])

In [24]:
# np.linspace(x,y,z) -> generates z data points in the rnage x to y in array.

np.linspace(1,5,20)
# generates 20 data points in the range 1 to 5 in array.

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [25]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [27]:
np.linspace(1,5,20,retstep=True)
# retstep -> gives jump size

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [30]:
# np.logspace(x,y,z) -> works same as linspace but give log of each value with base z.

np.logspace(1,5,10)
# genera

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [31]:
# np.zeros() -> generates array of zero.

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
# np.ones() -> generates array with 1.

np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [40]:
np.ones((3,4,5)) + 5

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [43]:
# np.empty() -> creates empty array.

np.empty((2,3))

array([[4.63817398e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [44]:
# np.eye() -> creates identy matrix where diagonal elements is one.

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
a = np.eye(4)

In [48]:
# shape -> give rows x columns
a.shape

(4, 4)

In [49]:
# size -> give no of elements in the array
a.size

16

In [50]:
#ndim -> gives dimension of the array
a.ndim

2

In [51]:
a1 = np.random.randn(3,4)

In [52]:
a1

array([[-0.79429792, -1.00119592, -1.69093043,  0.16423012],
       [-1.05541077,  0.31087485,  0.79321961, -1.14239609],
       [-0.38762595,  0.63630631, -0.1027098 , -1.92731428]])

In [59]:
# Accessing the element of the array.
# array[row_index][column_index]

a1[1][2]

0.7932196117855909

In [60]:
a1[0:2, 0:2]

array([[-0.79429792, -1.00119592],
       [-1.05541077,  0.31087485]])

In [61]:
a1[1:, 2:]

array([[ 0.79321961, -1.14239609],
       [-0.1027098 , -1.92731428]])

In [64]:
# np.random.randint -> generates array with integer values.

m1 = np.random.randint(1,3,(3,3))

In [65]:
m1

array([[1, 1, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [66]:
m2 = np.random.randint(2,4,(3,3))

In [67]:
m2

array([[2, 2, 2],
       [3, 2, 3],
       [3, 2, 3]])

In [70]:
# m1*m2 is not a matrix multiplication, it just a element vise multiplication.

m1*m2

array([[2, 2, 4],
       [3, 4, 3],
       [3, 4, 3]])

In [72]:
# m1@m2 gives matrix multiplication.

m1@m2

array([[11,  8, 11],
       [11,  8, 11],
       [11,  8, 11]])

In [76]:
# np.sqrt() -> gives sq. root of elements in the array.

np.sqrt(m1)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [77]:
# np.log() -> gives log of elements in the array.

np.log(m1)

array([[0.        , 0.        , 0.69314718],
       [0.        , 0.69314718, 0.        ],
       [0.        , 0.69314718, 0.        ]])

In [80]:
# np.log() -> gives log to the base 10 of elements in the array.

np.log10(m1)

array([[0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ]])

In [81]:
# np.exp() -> give exponential of values in the array.

np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])